# Generated by Django 4.0.6 on 2022-10-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_useraccount_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
    ]
