# Generated by Django 4.0.6 on 2022-10-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_first_name_useraccount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
